Modify Address field in multiple models
gcivil-nyu-org/INET-Monday-Spring2023-Team-5 pull request #107
Opened 2023-04-08 09:50 UTC by AlfaroukSaleh

- Divided the Address of Businesses to multiple fields ( Address1 Address2, City, State, Zip Code).
- Removed the Address field from Listing model
- Modified Test files to adapt the changes.
- Modified the Html files to adapt the changes.
- Set some fields in the Html files to required.

2023-04-09 01:43 UTC, moringspeaker commented
Bro, you don't have to change our backend model, I've done this in a frontend way, I just add two more input boxes and then concat them into one address, here is my version
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/55912169/230749966-0d44f458-fd2a-48d4-80b9-aad147598771.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/55912169/230749970-bb955894-9372-40bb-be67-3b82cdddb5ac.png">

2023-04-09 06:40 UTC, StephanieHou commented
Same comment I made in Chenyu's PR. We want it in the backend model because we are going to pull the zipcode or whatever else part of the address to filter the businesses.

2023-04-10 19:23 UTC, vchrombie requested changes
Overall it looks good @AlfaroukSaleh 

Just a few nits here and there. I can do the suggestions myself, I just need an ack from you.

Please let me know.

2023-04-10 19:23 UTC, vchrombie commented on users/models.py
> +    address = models.CharField(max_length=100, blank=True)
If we have decided to remove the address from the listing items, does it make sense to remove it completely from the model instead of hiding it?

2023-04-10 19:23 UTC, vchrombie commented on users/templates/users/add_listing.html
> +  <!-- <input type="text" name="address" placeholder="Listing Address" /> -->
same as above

2023-04-10 19:23 UTC, vchrombie commented on users/templates/users/view_listing.html
> +      <p>{{ listing.address }}</p> -->
same as above

2023-04-10 19:23 UTC, vchrombie commented on users/views.py
> +                # address=request.POST["address"],
same as above

2023-04-18 15:06 UTC, StephanieHou commented
@vchrombie @AlfaroukSaleh Please review changes again with new restructured code in develop.

2023-05-04 19:54 UTC, vchrombie commented
Not doing this at the moment since it doesn't add much value, we could come back at this some later point.

2023-05-04 19:54 UTC, closed without merging