Loading speed up
gcivil-nyu-org/INET-Monday-Spring2023-Team-5 pull request #110
Opened 2023-04-09 22:25 UTC by moringspeaker

I found out that our neighborhood page loads too slow due to bs icon which will be loaded from Bootstrap cdn in every iteration. So I stored it in directory: /static/bootsrap_icon/. And I also wrote some dynamically updating DOM JS script just for fun.

2023-04-09 23:50 UTC, vchrombie requested changes
I guess this PR needs some re-work and discussion.

2023-04-09 23:50 UTC, vchrombie commented on .gitignore
> +.gitignore
all these changes are not related and not useful

it would be great if you can remove them

2023-04-09 23:50 UTC, vchrombie commented on neighborhood/views.py
> +    neighborhoods_json = serializers.serialize("json", neighborhoods)
```suggestion
    neighborhoods = serializers.serialize("json", neighborhoods)
```

2023-04-09 23:50 UTC, vchrombie commented on neighborhood/views.py
> +    context["neighborhoods"] = neighborhoods_json
I would suggest to revert this change as it doesn't really improve anything. The previous change just works the same way.

Please let me know if I am missing anything.

2023-04-09 23:50 UTC, vchrombie commented on tests/test_views.py
> +        self.assertEqual(p, tp["name"])
Please revert this change. The aim of the test is to check the the neighborhoods view and the count is just fine. I would suggest we keep the tests similar.

2023-04-10 21:56 UTC, moringspeaker commented
I don't think it's a Mapbox problem cause I tested it, it's because in this page we try to fetch a Bs icon everytime, but for the backend part, I admit I just write them for better mathing my frontend JS script and there's actually no improvement

2023-04-10 22:55 UTC, vchrombie commented
> I don't think it's a Mapbox problem cause I tested it, it's because in this page we try to fetch a Bs icon everytime, but for the backend part, I admit I just write them for better mathing my frontend JS script and there's actually no improvement

I wasn't really convinced until you showed us in the meeting. But, I need to appreciate your work @moringspeaker. Thanks for all your experimentation.

Please let me know if you need help with the PR changes.

2023-04-11 00:42 UTC, vchrombie commented
Rework was done in #121, this PR will be automatically closed when the other one is merged

2023-04-11 17:39 UTC, closed without merging